export const tags = [
  { tag: "Healthy", id: 1 },
  { tag: "Low fat", id: 2 },
  { tag: "Vegetarian", id: 3 },
  { tag: "Kid foods", id: 4 },
  { tag: "Vitamins", id: 5 },
  { tag: "Bread", id: 6 },
  { tag: "Meat", id: 7 },
  { tag: "Snacks", id: 8 },
  { tag: "Tiffin", id: 9 },
  { tag: "Lunch", id: 10 },
  { tag: "Dinner", id: 11 },
  { tag: "Breakfast", id: 12 },
  { tag: "Fruit", id: 13 },
];
